# Generated by Django 2.2 on 2019-02-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
