# Generated by Django 2.2 on 2019-02-27 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_auto_20190227_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
